version: '3'

services:
  todo-app:
    build:
      context: ./app       # Context for the Flask app Dockerfile (relative to the docker-compose.yml location)
      dockerfile: Dockerfile  # Name of the Dockerfile inside 'app' directory
    container_name: todo-app
    ports:
      - "5000:5000"
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
    depends_on:
      - mongo

  mongo:
    image: mongo:latest    # Use official MongoDB image from Docker Hub
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db  # Persist MongoDB data on your local filesystem